# -*- coding: utf-8 -*-
"""IA2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xh9g-RyMoPOfvt7rjxbZbW7MCtxcWZkY
"""

#1
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Minimum of the array is:", arr.min())
print("Maximum of the array is:", arr.max())
print("The sum of the array is:", arr.sum())
print("The mean of the array is:", arr.mean())
print("The standard deviation of the array is", arr.std())

#2
import numpy as np
health_data=np.array([[160,70,30],[165,65,35],[170,75,40]])
normalization_std = health_data/ health_data.std(1)
normalization_mean = health_data/health_data. mean(0)

#3
import numpy as np
arr=np.array({'A':[98,56,78,85,23], 'B':[87,48,90,86,68], 'C':[85,34,9,32,-1]})
print(arr)
for i in arr:
sum = sum +
  new_arr= j.append()

#4
import numpy as np
np.linspace(15,25,24)

#5
import numpy as np
daily_closing_prices = np.array([100,102,98,105,107,110,108,112,115,118,120])
window_size=5
daily_closing_prices.mean(window_size)

#6

#7
import numpy as np
properties_matrix =np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(properties_matrix)

#8
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,9],ndmin=3)
print(arr)

#9
import numpy as np
import pandas as pd
data = {'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
        'Age':[25,30,35,40,45,50,55],
        'City':['New York','Los Angeles','Chicago','Houston','Phoenix','Miami','Boston'],
        'Department':['HR','IT','Finance','Marketing','Sales','IT','HR']}
df=pd.DataFrame(data)
age_df = df[df['age'] < 45]

#10
import numpy as np
import pandas as pd
data={'Department':
 ['Electronics','Electronics', 'Clothing', 'Clothing','HomeGoods'],
'Salesperson': ['Alice','Bob','Charlie','David','Eve'],
'Sales':[70000,50000,30000,40000,60000]}
average_price = data['Sales'].mean()

#11

#12

#13

#14

#15