# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFOYUFqcnaHsI_KIC2ipktFQGBlGXpr6
"""

import numpy as np
import pandas as pd
import warnings as wr
wr.filterwarnings('ignore')

#1.
data=pd.read_csv(r"/content/Final Dataset - IPL.csv")
df=pd.DataFrame(data)
df.info()

df.head(10)

df.dtypes

#2
missing_values = data.isna().sum()
print(missing_values)

dup = data.duplicated().sum()
print(dup)

#3
df.describe()

mean_data = data.mean()
print('Mean:',mean_data)
median_data = data.median()
print('Median:',median_data)
mode_data = data.mode()
print('Mode:',mode_data)
std_values = data.std()
print('Standard deviation:',std_values)
range_values = data['first_inings_score'].max() - data['first_inings_score'].min()
print('Range', range_values)
variance_values = data.var()
print('Variance:',variance_values)

df=df.to_string()

#4
import matplotlib.pyplot as plt
import seaborn as snp

#5
correlation_matrix = df.corr()
print(correlation_matrix)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as snp
df = pd.DataFrame(data)

#barchart
score= df.groupby('match_id')['second_ings_score'].sum()
plt.figure =(10,7)
score.plot(kind='bar')
plt.title(score)
plt.xlabel()
plt.ylabel()
plt.legend()
plt.show()

#piechart
p_category = df.groupby('match_id')['second_ings_score'].sum()
plt.figure(figsize=(6,6))
p_category.plot(kind='pie', autopct='%1.1f%%',labels=df['match id'])
plt.ylabel('')
plt.title('Score by match id')
plt.show()

#line chart
 l_category = df.groupby('match_id')['second_ings_match'].sum()
 l_category.plot(kind= 'line', marker = 0)
 plt.ylabel('')
 plt.xticks(rotation=90)
 plt.grid(True)
 plt.title('Average Score')
 plt.show()

#scatter
plt.figure(figsize=(10, 6))
data['Final Dataset'].value_counts().sort_index().plot(kind='scatter')
plt.title('Scatter Plot')
plt.xlabel('team1')
plt.ylabel('second_ings_wkt')
plt.show()

data['']

df.head(5)

#6 Outlier
import numpy as np
import seaborn as sns
numeric_cols = ['first_ings_score	', 'second_inings_score']
df_zscores = df[numeric_cols].apply(lambda x: np.abs((x - x.mean()) / x.std()))
outliers = df_zscores > 3
outliers_data = df[outliers.any(axis=1)]
print("Outliers:")
print(outliers_data)
plt.figure(figsize=(10, 6))
sns.boxplot(data=df[numeric_cols])
plt.title('Boxplot of first_ings_score, scecond_inings_score')
plt.xlabel('Features')
plt.ylabel('Values')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#7
def barchart():
  score= df.groupby(['venue','match_id'])['highscore'].sum()
  plt.figure =(10,7)
  score.plot(kind='bar')
  plt.title(score)
  plt.xlabel()
  plt.ylabel()
  plt.legend()
  plt.show()

def piechart():
  p1_category = df.groupby(['venue','match_id'])['highscore'].sum()
  plt.figure(figsize=(6,6))
  p1_category.plot(kind='pie', autopct='%1.1f%%',labels=df['match id'])
  plt.ylabel('')
  plt.title('Score by match id')
  plt.show()

def linechart():
 l1_category = df.groupby(['venue','match_id'])['highscore'].sum()
 l1_category.plot(kind= 'line', marker = 0)
 plt.ylabel('')
 plt.xticks(rotation=90)
 plt.grid(True)
 plt.title('Average Score')
 plt.show()

barchart()
piechart()
linechart()