# -*- coding: utf-8 -*-
"""Lvadsusr_188.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBamrvMJ2tubp1iGHlfDJE17nDeY513d
"""

#1.
length=float(input("Enter the length of the area which you want to calculate in meters: "))
width = float(input("Enter the width of the area which you want to calculate in meters: "))
area= length* width
print("The area calculated is", area)
if (area>100 and area < 500):
  print("The area is small")
elif(area > 500 and area < 1000):
    print("The area is medium")
else:
    print("The area is large")

#2
weight = int(input("Enter your weigth in kgs: "))
height = float(input("Enter your height in metres"))
bmi_calculation = weight/(height**2)
print("The calculated bmi index is", bmi_calculation)

#3
student_records = {"Physics": "88", "Chemistry": "94", "Biology": "87", "Maths": "92", "English":"72"}
print(student_records.values())
print(student_records.keys())
print(student_records.items())

#4
age = int(input("Enter your age:"))

if(age<=12):
  print("Category: Children")
elif(age>=13 and age<=19 ):
  print("Category: Teen")
elif(age>=18 and age<=40):
  print("Category: Adult")
else:
  print("Category: Senior")

#5
list_1=("2977", "5678", "2357", "2479", "1290")
print("The even numbereed subscribers are:")
for i in range(len(list_1)):
  if(int(list_1[i])%2==0):
    print(list_1[i])

#6
password ="ABC@123"

while True:
 pas= input("Enter your password:")
 if(pas== password):
    print("Login successful")
    break;
 print("Incorrect Credentials:")

#7
import math
set_1={"4.6", "4.9","3.2","3.0"}
sum = 0
def avg():
  for i in range(len(set_1)):
  sum = sum+ (int(set_1[i]))
avg = sum/len(set_1)

avg()
print("The average from customer review is:", avg)

#8
list_1= input.list()
for i in range(len(list_1)):
  if(list_1[i] == "A", OR list_1[i] =="E", OR list_1[i] == "I", OR list_1[i]== "O", OR list_1[i]=="U", OR list_1[i] == "a", OR list_1[i] =="e", OR list_1[i] == "i", OR list_1[i]== "o", OR list_1[i]=="u"):
    vowel=vowel+1
print("The no of vowels"vowel)

#9
import datetime
date = datetime.now()

#10
p=(int(input("Enter the principal amount")))
t=(int(input("Enter the time")))
r=(int(input("Enter the rate")))
inte = 0
try: print("Perform banking calculations")
     inte = (p*t*r)/100
     print("Interest is", inte)

except: print("Error Handling")

#11
try: n=(int(input("Enter the number")))
    print(n)
except: print("Error Handling, invalid input")

#12
try:
    n1=(int(input("Enter the number")))
    n2=(int(input("Enter the number")))
    div= n1/n2
    print("div")
except: print("Error Handling,Division by zero not allowed")

#14
v = open('/content/sample_data/mnist_test.csv', 'r')
print(v.read())
v.close()

#15 v = open('/content/sample_data/mnist_test.csv', 'a')
print(v.append())
v.close()